name: coverage
'on': pull_request
jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: 18.x
      - uses: ArtiomTr/jest-coverage-report-action@v2.3.0
        with:
            test-script: pnpm run test:coverage
            package-manager: pnpm