runs-on: ubuntu-latest
steps:
  - uses: actions/checkout@v4
  - name: Install pnpm
  - uses: pnpm/action-setup@v3
      with:
        version: 9
  - name: Use Node.js
  - uses: actions/setup-node@v4
      with:
        node-version: "18.x"
        cache: 'pnpm'
  - name: Install dependencies
      run: pnpm install
  - name: Run eslint on changed files
    uses: tj-actions/eslint-changed-files@v25
    with:
      config_path: .eslintrc
      extra_args: '--max-warnings=0'